language: erlang

services:
  - docker

before_install:
  - docker pull postgres:10.12
  - docker run --name epgsql -e POSTGRES_PASSWORD=mysecretpassword -d postgres:10.12
  - docker ps -a

matrix:
  include:
    - otp_release: 22.2
    - otp_release: 21.3
    - otp_release: 20.3
    - otp_release: 19.3
    - otp_release: 18.3
      dist: trusty

script:
  - '[ "$TRAVIS_OTP_RELEASE" = "18.3" ] || make elvis' # TODO: remove the guard when OTP18 support is dropped
  - make test
  - make edoc
  - make dialyzer
